version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - run: |
          sudo npm install -g parcel-bundler
          npm install
          parcel build
